name: Increment Version and Tag

on:
  push:
    branches: [ "main" ] 
  pull_request:
    branches: [ "main" ]

jobs:
  increment-version:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Get the last tag
        id: get-last-tag
        run: |
          LAST_TAG=$(git describe --tags `git rev-list --tags --max-count=1`)
          echo "Last Tag: $LAST_TAG"
          echo "::set-output name=last_tag::$LAST_TAG"

      - name: Parse the last tag
        id: parse-last-tag
        run: |
          LAST_TAG="${{ steps.get-last-tag.outputs.last_tag }}"
          # Remove the 'v' prefix if present
          TAG=${LAST_TAG#v}
          IFS='.' read -ra PARTS <<< "$TAG"
          MAJOR_LAST="${PARTS[0]}"
          MINOR_LAST="${PARTS[1]}"
          PATCH_LAST="${PARTS[2]}"
          echo "Major from Last Tag: $MAJOR_LAST"
          echo "Minor from Last Tag: $MINOR_LAST"
          echo "Patch from Last Tag: $PATCH_LAST"
          echo "::set-output name=major_last::$MAJOR_LAST"
          echo "::set-output name=minor_last::$MINOR_LAST"
          echo "::set-output name=patch_last::$PATCH_LAST"

      - name: Get current version from version.json
        id: get-version-json
        run: |
          CURRENT_VERSION_JSON=$(jq -r .version version.json)
          echo "Current Version from version.json: $CURRENT_VERSION_JSON"
          echo "::set-output name=current_version_json::$CURRENT_VERSION_JSON"

      - name: Parse current version from version.json
        id: parse-version-json
        run: |
          CURRENT_VERSION_JSON="${{ steps.get-version-json.outputs.current_version_json }}"
          IFS='.' read -ra PARTS_JSON <<< "$CURRENT_VERSION_JSON"
          MAJOR_JSON="${PARTS_JSON[0]}"
          MINOR_JSON="${PARTS_JSON[1]}"
          PATCH_JSON="${PARTS_JSON[2]}"
          echo "Major from version.json: $MAJOR_JSON"
          echo "Minor from version.json: $MINOR_JSON"
          echo "Patch from version.json: $PATCH_JSON"
          echo "::set-output name=major_json::$MAJOR_JSON"
          echo "::set-output name=minor_json::$MINOR_JSON"
          echo "::set-output name=patch_json::$PATCH_JSON"

      - name: Calculate new version
        id: calculate-new-version
        run: |
          MAJOR_LAST="${{ steps.parse-last-tag.outputs.major_last }}"
          MINOR_LAST="${{ steps.parse-last-tag.outputs.minor_last }}"
          MAJOR_JSON="${{ steps.parse-version-json.outputs.major_json }}"
          MINOR_JSON="${{ steps.parse-version-json.outputs.minor_json }}"
          PATCH_JSON="${{ steps.parse-version-json.outputs.patch_json }}"
          
          if [[ "$MAJOR_LAST" -lt "$MAJOR_JSON" || "$MINOR_LAST" -lt "$MINOR_JSON" ]]; then
            NEW_MAJOR="$MAJOR_JSON"
            NEW_MINOR="$MINOR_JSON"
            NEW_PATCH=0
          else
            NEW_MAJOR="$MAJOR_LAST"
            NEW_MINOR="$MINOR_LAST"
            NEW_PATCH=$((PATCH_JSON + 1))
          fi

          NEW_VERSION="$NEW_MAJOR.$NEW_MINOR.$NEW_PATCH"
          echo "New Version: $NEW_VERSION"
          echo "::set-output name=new_version::$NEW_VERSION"

      - name: Create and push new tag
        if: steps.calculate-new-version.outputs.new_version != ''
        run: |
          NEW_VERSION="${{ steps.calculate-new-version.outputs.new_version }}"
          git tag -a "v$NEW_VERSION" -m "Incremented version to v$NEW_VERSION"
          git push origin "v$NEW_VERSION"
